--- 
title: "Milestone 3" 
author: "Niel Schrage" 
date: "2/21/2020" 
output: html_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The paper that I have chosen to replicate for my final project is ["What the
Demolition of Public Housing Teaches Us about the Impact of Racial Threat on
Political Behavior"](https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12156)
by [Ryan D. Enos](http://ryandenos.com/). The central research question of this
paper is: How does the context in which a person lives affect his or her
political behavior? Enos studided the 2000-2004 reconstruction of public housing
in Chicago -- a period of time with major demographic shifts from previously
racially heterogenios neighborhoods to predominantly white homogenous
neighborhoods. He found that upon the removal of African Americans from
neighborhoods, the voting turnout of the white voters' remaining dropped by more
than 10 percentage points. Additionally, his research suggests that proximity
was also related to an increase in voting for conservative candidates.
Ultimately, Enos concludes that the context in which a person lives affect his
or her political behavior quite considerably.

Here is the link to my [repository](https://github.com/nschrage/replication_2).