---
title: 'Milestone #2'
author: "Niel Schrage"
date: "2/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

> Milestone #2. Create a repo with the data for the paper which you are considering. Create an Rmd that does something with that data. (Can be a single R command like summary().) Submit the html generated by that Rmd. It is OK, for now, if you don’t yet have the data for your paper. But you still must submit milestone #2, which requires data. What to do? Easy! Pick a back-up paper, with data available, and submit milestone #2 (and #3 and . . .) using that second-choice paper. As soon as you get data for your main paper, you can switch back. Always include a link to the repo, perhaps in footnote, in any html milestone submission.

## Milestone #2

1. Update

After speaking with Alice, I decided to switch papers. I am now replicating ["What the Demolition of Public Housing Teaches Us about the Impact of Racial Threat on Political Behavior"](https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12156), by Ryan D. Enos.

[Replication Data](http://dvn.iq.harvard.edu/dvn/dv/ajps)

test